triggers:
- envs: []
  last_enabled_at: 2024-04-14 14:40:21.179658
  name: first_pipeline
  pipeline_uuid: eq_api_to_gcs
  schedule_interval: '@daily'
  schedule_type: time
  settings:
    landing_time_enabled: false
  sla: null
  start_time: 2024-04-15 07:00:00
  status: inactive
  variables:
    start_date: '2020-01-01'
